# EJERCICIO 6
valorDinero = float(input("Ingrese un monto a retirar: "));
print();
cantidadBilletes1000 = int(valorDinero / 1000);
cantidadBilletes500 = int(valorDinero / 500);
cantidadBilletes200 = int(valorDinero / 200);
cantidadBilletes100 = int(valorDinero / 100);
cantidadBilletes50 = int(valorDinero / 50);
cantidadBilletes20 = int(valorDinero / 20);
cantidadMonedas10 = int(valorDinero / 10);
cantidadMonedas5 = int(valorDinero / 5);
cantidadMonedas2 = int(valorDinero / 2);
cantidadMonedas1 = int(valorDinero / 1);
print("La cantidad de billetes de 1000 ARS que entran en su monto es:", cantidadBilletes1000);
print("La cantidad de billetes de 500 ARS que entran en su monto es:", cantidadBilletes500);
print("La cantidad de billetes de 200 ARS que entran en su monto es:", cantidadBilletes200);
print("La cantidad de billetes de 100 ARS que entran en su monto es:", cantidadBilletes100);
print("La cantidad de billetes de 50 ARS que entran en su monto es:", cantidadBilletes50);
print("La cantidad de billetes de 20 ARS que entran en su monto es:", cantidadBilletes20);
print("La cantidad de monedas de 10 ARS que entran en su monto es:", cantidadMonedas10);
print("La cantidad de monedas de 5 ARS que entran en su monto es:", cantidadMonedas5);
print("La cantidad de monedas de 2 ARS que entran en su monto es:", cantidadMonedas2);
print("La cantidad de monedad de 1 ARS que entran en su monto es:", cantidadMonedas1);